# These are supported funding model platforms

custom: ["https://lexlink.com.es", asesorialegaldigital.com.es] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
#github: [davidgzs]
#patreon: octocat
#tidelift: npm/octo-package
#custom: ["https://www.paypal.me/octocat", octocat.com]
